### ISSUE TITLE
[FEATURE] Integrate with Mosaic AI gateway

### ISSUE THREAD

**Issue by sathishgang-db** [stikkireddy/mlflow-extensions#58]
**Is your feature request related to a problem? Please describe.**
If there's a way to take the model endpoint and make it be managed entirely using the mosaic AI gateway, that would open up all of the features from that product - usage tracking, payload logging, guardrails, ratelimiting etc. Would be an amazing add on to any SoTA model supported

This would allow users to cleanly compare between new supported models (maybe domain specific) and other frontier proprietary provider models by setting up routing rules as well. Will simplify model selection and allow for science based reasoning for the choices made during evals.

**Comment by stikkireddy** [comment]
completed as part of v0.15.0 and documented here: https://stikkireddy.github.io/mlflow-extensions/getting-started/ezdeploylite/#registering-into-mosaic-ai-gateway
