### ISSUE TITLE
[FEATURE] show base url when deploying on job cluster with EZDeployLight

### ISSUE THREAD

**Issue by juanlamadrid20** [stikkireddy/mlflow-extensions#62]
I would like the base_url to show as output from deployment job. 
```python
base_url = get_ezdeploy_lite_openai_url(deployment_name)
``` 
This allows me to easily get the base_url needed to connect clients or model serving endpoints.

Today I have to run above code on separate notebook to get the base url . Instead I would prefer on every restart of the job task to get the latest base url.

**Comment by stikkireddy** [comment]
completed as part of v0.15.0
